const getForeignKeyQuery = (mainTable, joinTable) => {
    return "SELECT KCU.COLUMN_NAME AS FK_COLUMN" 
    + " FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS TCO"
    + " JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE KCU ON TCO.CONSTRAINT_SCHEMA = KCU.CONSTRAINT_SCHEMA AND TCO.CONSTRAINT_NAME = KCU.CONSTRAINT_NAME"
    + " JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RCO ON TCO.CONSTRAINT_SCHEMA = RCO.CONSTRAINT_SCHEMA AND TCO.CONSTRAINT_NAME = RCO.CONSTRAINT_NAME"
    + " JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE REL_KCU ON RCO.UNIQUE_CONSTRAINT_SCHEMA = REL_KCU.CONSTRAINT_SCHEMA AND RCO.UNIQUE_CONSTRAINT_NAME = REL_KCU.CONSTRAINT_NAME AND KCU.ORDINAL_POSITION = REL_KCU.ORDINAL_POSITION"
    + " WHERE TCO.CONSTRAINT_TYPE = 'FOREIGN KEY' AND REL_KCU.TABLE_NAME = '"
    + joinTable 
    + "' AND KCU.TABLE_NAME = '"
    + mainTable + "' ORDER BY KCU.TABLE_SCHEMA, KCU.TABLE_NAME, KCU.ORDINAL_POSITION";
};

module.exports = {
    getForeignKeyQuery
}