FROM node:14.15.0
WORKDIR /server
COPY package*.json ./
RUN npm set strict-ssl false
RUN npm install -g
COPY . /server
ENV PORT=3000
ENV TEST_ENV_VARIABLE="Environment variable is coming across"
ENV CONNECTION_STRING="postgresql://yau1:pass12@yash-api-db:5432/yashapi"
EXPOSE 8085
CMD ["npm", "run", "startdev"]
